// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChwQKkGpiRhbq9RB3pAk1lMMxrnXi1SR8',
    appId: '1:635677029777:web:81fcadb9382b28a9631630',
    messagingSenderId: '635677029777',
    projectId: 'connect-app-907bd',
    authDomain: 'connect-app-907bd.firebaseapp.com',
    storageBucket: 'connect-app-907bd.appspot.com',
    measurementId: 'G-PVD86LB649',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbmXiKpGjff4nXeb8rfnw9lYasFYtjlg',
    appId: '1:635677029777:android:f44dab9aa8f97e7e631630',
    messagingSenderId: '635677029777',
    projectId: 'connect-app-907bd',
    storageBucket: 'connect-app-907bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgG1rWgzpUmfX8aw382m39CFbsw3Y6wgg',
    appId: '1:635677029777:ios:cf9e5f0cdd732481631630',
    messagingSenderId: '635677029777',
    projectId: 'connect-app-907bd',
    storageBucket: 'connect-app-907bd.appspot.com',
    iosBundleId: 'com.example.connectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgG1rWgzpUmfX8aw382m39CFbsw3Y6wgg',
    appId: '1:635677029777:ios:2e60b0d44141b05e631630',
    messagingSenderId: '635677029777',
    projectId: 'connect-app-907bd',
    storageBucket: 'connect-app-907bd.appspot.com',
    iosBundleId: 'com.example.connectApp.RunnerTests',
  );
}
